[build]
  publish = "."
  functions = "netlify/functions"
  command = "echo 'no build step needed'"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/producto/:id"
  to = "/.netlify/functions/product-share?id=:id"
  status = 200
